"""Initial version

Revision ID: 981244b0ac7a
Revises: 
Create Date: 2023-11-15 16:45:28.348422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981244b0ac7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthdays')
    # ### end Alembic commands ###
